events {}

http {

    server {

        listen 80;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        location /api/ {
            proxy_pass http://internal-three-tier-internal-alb-1282504073.ap-south-1.elb.amazonaws.com/;
        }

    }

}