[webservers]
web ansible_host=13.201.66.146 ansible_user=ubuntu

[appservers]
app ansible_host=10.0.2.52 ansible_user=ubuntu ansible_ssh_common_args='-o ProxyJump=ubuntu@13.201.66.146 -o StrictHostKeyChecking=no -o ForwardAgent=yes'