[webservers]
web ansible_host=13.233.94.62 ansible_user=ubuntu

[appservers]
app ansible_host=10.0.2.68 ansible_user=ubuntu ansible_ssh_common_args='-o ProxyJump=ubuntu@13.233.94.62 -o StrictHostKeyChecking=no -o ForwardAgent=yes'